name: Deploy Celestial from tarball to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository, which contains the tarball and this workflow
      - uses: actions/checkout@v3
      # Extract the tarball into the workspace
      - name: Extract Celestial project
        run: |
          tar -xzf celestial_site.tar.gz
      # Install dependencies and build the site from the extracted folder
      - name: Install dependencies
        run: |
          cd Celestial && npm ci
      - name: Build site
        run: |
          cd Celestial && npm run build
      # Deploy the built site to GitHub Pages using the gh-pages action
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Celestial/dist